# **Parte 2 - Arrays de Numpy**

### **¿Qué es NumPy?**

*   Una biblioteca para python: ndarray + ufunc.
*   Los arrayas multidimencionales (ndarray) nos permiten almacenar datos de manera estructurada.
*   Las funciones universales (ufunc) nos permiten operar con esos datos de manera eficiente.

Python esta organizado en módulos, que son archivos con extensión .py  que contienen funciones, variables y otros objetos, y paquetes, que son conjuntos de módulos. Cuando queremos utilizar objetos que están definidos en un módulo tenemos que importarlo, y una vez que los hecmos hecho podemos usar el operador . para ir descendiendo en la jerarquía de paquetes y acceder al objeto que necesitamos. ***Por ejemplo, de esta manera importamos NumPy***



 

In [1]:
import numpy

Y de esta manera accedemos a la función norm, que calcula la norma (o módulo) de un array

In [2]:
numpy.linalg.norm

<function numpy.linalg.norm>

La función norm está dentro del paquete linalg, que a su vez está dentrp del paquete NumPy

La convención para importar NumPy siempre sera esta:

In [3]:
import numpy as np

Lo que hacemos es crear un alias al paquete NumPy de nombre np. Es simplemente una forma de abreviar el código. Esta forma de separar las funciones en paquetes (que se llaman **espacios de nombres** o *namespaces*) conduce a una mayor legibilidad del código y a la supresión de ambiguedades. 

Para encontrar ayuda sobre cierto tema podemos usar la función *lookfor*.

In [4]:
np.lookfor("solve")

Search results for 'solve'
--------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.linalg.lstsq
    Return the least-squares solution to a linear matrix equation.
numpy.linalg.tensorsolve
    Solve the tensor equation ``a x = b`` for x.
numpy.nditer.close
    close()
numpy.linalg._umath_linalg.solve
    solve the system a x = b, on the last two dimensions, broadcast to the rest.
numpy.linalg._umath_linalg.solve1
    solve the system a x = b, for b being a vector, broadcast in the outer dimensions.
numpy.distutils.misc_util.njoin
    Join two or more pathname components +
numpy.distutils.misc_util.minrelpath
    Resolve `..` and '.' from path.
numpy.distutils.system_info.UmfpackNotFoundError
    UMFPACK sparse solver (https://www.cise.ufl.edu/research/sparse/umfpack/)
numpy.shares_memory
    Determine if two arrays share memory
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.

### **Constantes y funciones**

Además de arrays, NumPy contiene también constantes y funciones matemáticas de uso cotidiano.

In [ ]:
np.e

2.718281828459045

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.log(2)

0.6931471805599453

### **¿Qué es exactamente un array?**

Un array de NumPy es una colección de N elementos, igual que una secuencia de Python (ej. una lista). Tiene las mismas propiedades de una secuencia y alguna más. Para crear un array, la forma mas directa es pasarle una secuencia a la función np.array.

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

Los arrays de NumPy son homogeneos, es decir, todos sus elementos son del mismo tipo. Si le pasamos a `np.array` una secuencia con objetos de tipos diferentes, ***promocionara*** todos al tipo con más información. Para acceder al tipo de array, podemos usar el atributo **`dtype`**.

In [ ]:
a = np.array([1, 2, 3.0])
print(a.dtype)

float64


In [ ]:
#CoSAS RAR4S
np.array([1, 2, "3"])

array(['1', '2', '3'], dtype='<U21')

Numpy intentara automáticamente construir un array con el tipo adecuado teniendo en cuenta los datos de entrada, aunque nosotros podemos forzarlo.

In [ ]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [ ]:
#Crear un array de numeros complejos
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

También podemos convertir un array de un tipo a otro utilizando el método **`.astype`**

In [ ]:
# recuperamos el array creado anteriormente a
a

array([1., 2., 3.])

In [ ]:
#lo convertimos a un array de enteros
a.astype(int)

array([1, 2, 3])

In [ ]:
#En el caso de todos los elementos sean numeros, una conversion estara permitida
#aun cuando los numeros sean cadena.
s = np.array([1, 2, "3"])
s.astype(int)

array([1, 2, 3])

Motivo de usar NumPy: eficiencia 

*   Los bucles son costosos.
*   Eliminar bucles: **Vectorizar** operaciones
*   Los bucles se ejecutan en Python, las operaciones vectorizadas en C
*   Las operaciones entre arrays de NumPy se realizan **elemento a elemento**.

Ejemplo:

<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbf{a_{ij}&space;=&space;b_{ij}&space;&plus;&space;c_{ij}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathbf{a_{ij}&space;=&space;b_{ij}&space;&plus;&space;c_{ij}}" title="\mathbf{a_{ij} = b_{ij} + c_{ij}}" /></a>


In [ ]:
N, M = 100, 100
a = np.empty(10000).reshape(N, M)
b = np.random.rand(10000).reshape(N, M)
c = np.random.rand(10000).reshape(N, M)

In [ ]:
%%timeit
for i in range(N):
    for j in range(M):
        a[i, j] = b[i, j] + c[i, j]

100 loops, best of 3: 5.67 ms per loop


In [ ]:
%%timeit
a = b + c

The slowest run took 97.14 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.11 µs per loop
