# **Indexación de arrays**

Una de las herramientas más importantes a la hora de trabajar es el indexado. Consiste en seleccionar elementos aislados o secciones de un array. La indexación que se presenta aqui es básica, pero existen técnicas de indexación avanzadas que convierten los arrays en herramientas potenticimas.

In [1]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]
             ])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Obtenemos la primera fila
a[0]

array([1, 2, 3])

In [ ]:
#Obtenemos el primer elemento de la primera fila
a[0][0]

1

In [ ]:
#Una alternativa que tiene NumPy es la siguiente forma
a[0, 0] #Obtenemos el primer elemento de la primera fila

1

In [ ]:
#Obtener todas la filas de la 2 y 3 columna, solución:
s1 = a[0:2,1:3]
s2 = a[:, 1:]
#ambas soluciones son equivalentes.
print(s1)
print("********")
print(s2)

[[2 3]
 [5 6]]
********
[[2 3]
 [5 6]]


In [ ]:
#Obtener todos los elementos pares de una fila
a[0, 0:3:2]  # => a[0, ::2]

array([1, 3])

Los índices se indican entre los corchetes justo despues del array. Recuerda que en Python la indexación empieza en 0. Si recuperamos el primer elemento de un array de dos dimensiones, obtendremos la primera fila.

# **Creación de arrays**

Muchos métodos y muy variados.


*   A partir de datos existentes: array, copy
*   Unos y ceros: empty, eye, zeros, *_like
*   Rangos: arange, linspace, logspace, meshgrid
*   Aleatorios: rand, randn



## **Unos y ceros**


*   empty(shape) crea una array con <basura>, equivalente a no inicializarlo, ligeramente más rapido que zeros y ones.
*   eye(N, M=none, k=0) crea un array con unos en una diagonal y ceros en el resto   
*   identity(n) devuelve la matriz identidad
*  Las funciones *_like(a) construyen arrays con el mismo tamaño que uno dado




In [ ]:
np.empty((3,4))

array([[2.78409549e-316, 2.10077583e-312, 2.29175545e-312,
        2.31297541e-312],
       [2.01589600e-312, 2.46151512e-312, 2.10077583e-312,
        8.48798317e-313],
       [2.48273508e-312, 8.70018275e-313, 8.70018275e-313,
        4.44659081e-323]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5).astype(int)  #matriz en forma de numeros enteros

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
i3 = np.identity(3)
i3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
i3.shape

(3, 3)

In [ ]:
np.ones(i3.shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones_like(i3)  #recibe una matriz y la crea de la misma dimención pero de unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## **Rangos**

*  linspace(start, stop, num=50) devuelve números equiespaciados dentro de un intervalo.
*  logspace(start, stop, num=50, base=10.0) devuelve números equiespaciados según una escala logaritmica. 
*  meshgrid(x1, x2, ...) devuelve matrices de n-coordenadas.

In [3]:
np.linspace(0,1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
np.logspace(0, 3, num=10, base=10.0)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

La función **`meshgrid()`**, permite generar matrices de coordenadas. Como se muestra a continuación.

In [9]:
x = np.linspace(0, 1, num=4)
y = np.linspace(0, 1, num=4)

xx, yy = np.meshgrid(x,y)

In [10]:
xx, yy  #la matriz xx varia por filas y la matriz yy varia por columnas
#La función meshgrid es util para representar funciones en 2-D (en este caso) y
#3-D
# Si se toma un elemento de cada matriz, "estare representado" un pixel (para imagenes)
# un punto (en plano cartesiano), etc.

(array([[0.        , 0.33333333, 0.66666667, 1.        ],
        [0.        , 0.33333333, 0.66666667, 1.        ],
        [0.        , 0.33333333, 0.66666667, 1.        ],
        [0.        , 0.33333333, 0.66666667, 1.        ]]),
 array([[0.        , 0.        , 0.        , 0.        ],
        [0.33333333, 0.33333333, 0.33333333, 0.33333333],
        [0.66666667, 0.66666667, 0.66666667, 0.66666667],
        [1.        , 1.        , 1.        , 1.        ]]))