# **NUMPY**

El nombre proviene de "Numerical Python", es una libreria fundamental para 
el cálculo cientifico en Pytho, un ámbito en el que los tipos estándar de Python serán insuficientes.
De forma gral. NumPy, nos permitira trabajar con arrays multidimencionales de forma muy rápida y eficiente.

NumPy implementa una clase(recordar que una clase es un tipo de dato abstracto) ***ndarray***.

***Nota:*** Se debe tener cuidado que es TDA que determinadas funciones de otras librerias como el ejemplo Math, no estan diseñadas para operar con arrays.

Antes de comenzar, se debe *importar NumPy*, como cualquier otra libreria, la siguiente forma de importar, nos evita problemas con otras librerias y se considera un estandar.

In [5]:
import numpy as np
np.version.version

'1.18.5'

**Creación de un array**

In [ ]:
a = np.array([1,2,3])
print("1D array:")
print(a)

b = np.array([(1,2,3),(4,5,7)])
print("2D array:")
print(b)

1D array:
[1 2 3]
2D array:
[[1 2 3]
 [4 5 7]]


**Listas Nativas Python VS Arrays de Numpy**

In [ ]:
#Comparando el USO de memoria utilizada en ejecución de lista de python vs arrays de NumpY
import sys
S = range(1000)
print("Resultado lista de Python: ")
print(sys.getsizeof(5)*len(S))

D = np.arange(1000)
print("Resultado NumPy ARRAY: ")
print(D.size * D.itemsize)

Resultado lista de Python: 
28000
Resultado NumPy ARRAY: 
8000


In [ ]:
#Comparando tiempo de ejecución de lista de python vs arrays de NumpY
import time

SIZE = 1000000

L1 = range(SIZE)
L2 = range(SIZE)
 
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print("Resultado lista de Python")
print((time.time() - start) * 1000)
print()

start = time.time()
result = A1 + A2
print("Resultado NumPy array")
print((time.time() - start) * 1000)


Resultado lista de Python
204.8187255859375

Resultado NumPy array
55.82857131958008


In [ ]:
#Crear una matriz de unos - 3 filas por 4 Columnas

Matriz_unos = np.ones((3,4))
print(Matriz_unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Crear una matriz de ceros - 3 filas por 4 Columnas

Matriz_ceros = np.zeros((4,3))
print(Matriz_ceros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Crear una matriz con valores aleatorios

aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.37727906 0.82128859]
 [0.13653955 0.21500793]]


In [ ]:
#Crear una matriz vacia

vacia = np.empty((3,2),int)
print(vacia)

[[66636224        0]
 [       0        0]
 [       0        0]]


In [ ]:
#Crear una matriz con un solo valor en todas sus pocisiones

full = np.full((4,2),10)
print(full)

[[10 10]
 [10 10]
 [10 10]
 [10 10]]


In [ ]:
#Crear una matriz con valores espaciados uniformente

#Matriz de 0 - 30, con valores de separacion de 5 en 5
espacio1 = np.arange(0,30,5)
print(espacio1)

#Matriz de 0 a 30, con exactamente 6 valores, claro 6 puede cambiar maximo hasta 50
espacio2 = np.linspace(0,30,6)
print(espacio2)

[ 0  5 10 15 20 25]
[ 0.  6. 12. 18. 24. 30.]


In [ ]:
#Crear una matriz identidad

identidad1 = np.eye(3,3)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Conocer las dimensiones de una matriz

a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [ ]:
#Conocer el tipo de datos de un array

U = np.array([(1,2,4)])
print(U.dtype)

int64


In [ ]:
# Conocer el tamaño y la forma de la matriz

V = np.array([(1,2,3,4,5,6)])
print("El tamaño es: ",V.size)
print("La forma es: ",V.shape)

El tamaño es:  6
La forma es:  (1, 6)


In [ ]:
#Cambio de forma de una matriz
U = np.array([(8,6,9), (11,15,13)])
print(U)
V = U.reshape(3,2)
print(V)

[[ 8  6  9]
 [11 15 13]]
[[ 8  6]
 [ 9 11]
 [15 13]]


In [ ]:
#Extraer un solo valor de la matriz - el valor ubicado en la fila 0, columna 2

U = np.array([(8,6,9,4),(11,15,13,19)])
print(U[0,2])

9


In [ ]:
# Extraer los valores de todas las filas ubicados en la columna 3

V = np.array([(8,6,9,5),(11,15,13,20)])
print(V[0:,2])  #todas las filas de la columna 2 (recordar que se cuenta desde 0)

[ 9 13]


In [ ]:
# Encontrar el valor minimo, maximo y suma
U = np.array([(2,4,8)])
print(U.min())
print(U.max())
print(U.sum())

2
8
14


In [ ]:
#Obtener la raiz cuadrada y la desviación estandar

U = np.array([(1,2,3),(3,4,5)])
print(np.sqrt(U))
print(np.std(U))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [ ]:
#Calcular la suma,resta, multiplicacion

A = np.array([(1,2,3),(4,5,6)])
B = np.array([(1,1,1),(4,5,6)])
print(A + B)
print(A - B)
print(A * B)
print(A / B)

[[ 2  3  4]
 [ 8 10 12]]
[[0 1 2]
 [0 0 0]]
[[ 1  2  3]
 [16 25 36]]
[[1. 2. 3.]
 [1. 1. 1.]]
